### ISSUE TITLE
[Request] Airsonic Advanced

### ISSUE THREAD

**Issue by sic79** [A75G/docker-templates#17]
* Docker Link: https://hub.docker.com/r/airsonicadvanced/airsonic-advanced

And/or

* Git Link: https://github.com/airsonic-advanced/airsonic-advanced

**Comment by A75G** [comment]
Hopefully it should be up soon
https://github.com/A75G/docker-templates/commit/4855f097784e1be2e883c74da3936f7c159e7155

**Comment by sic79** [comment]
Nice :) Looking forward to test it

**Comment by sic79** [comment]
I had to add the variable "JAVA_OPTS: -Xms256m -Xmx512m" just like in the "original" airsonic docker from ls.io. This because I got some java out of memory errors when indexing my library. But other than that, it seems to work just fine :). Thank you very much

**Comment by A75G** [comment]
> 
> 
> I had to add the variable "JAVA_OPTS: -Xms256m -Xmx512m" just like in the "original" airsonic docker from ls.io. This because I got some java out of memory errors when indexing my library. But other than that, it seems to work just fine :). Thank you very much

Thank you for the notice ill add it to the template right away.
