### ISSUE TITLE
[Request] Weechat

### ISSUE THREAD

**Issue by sic79** [A75G/docker-templates#19]
* Docker Link: https://hub.docker.com/r/jkaberg/weechat/

And/or

* Git Link: https://github.com/jkaberg/dockerfiles/tree/master/weechat

**Comment by A75G** [comment]
Hey,
i have some questions
What does this docker do exectly?
Is there suppose to be webserver inside it or something?

I ran it and got files, inside port 9001 nothing

**Comment by sic79** [comment]
Hi, 

I have not tested the dockerized Weechat version so I doesn´t know exactly how that one works, but someway you should connect with ssh.

Weechat is a IRC chat client that is run in shell only so no webserver should be running, but there is a nice addon that adds that feature called GlowingBear -- https://github.com/glowing-bear/glowing-bear

**Comment by A75G** [comment]
Hello,
I'v added it to the list you test it out and tell me if anything is wrong.

**Comment by sic79** [comment]
Hi.

Sure, just tell me how to test.

**Comment by A75G** [comment]
Sorry for the delay i uploaded it but file type was wrong check after few hours in CA

**Comment by sic79** [comment]
No worries, thanks for trying to fix this docker to CA.

Tried it now but it did not start up.

I got this wierd looking errorlog, and what I can read from it is that the plugin folder or plugins seems to be missing

<details>
<summary>errorlog</summary>
[39m[1K [34m│
│[3G[39m[m[2;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin[3;24H[32m| [39m"/usr/lib/weechat/plugins/lua.so": Error loading shared[4;24H[32m| [39mlibrary liblua.so.5: No such file or directory (needed[5;24H[32m| [39mby /usr/lib/weechat/plugins/lua.so)[6;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C plugin,[7;24H[32m| [39mtry command to load scripts (/perl, /python, ...)[8;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin[9;24H[32m| [39m"/usr/lib/weechat/plugins/ruby.so": Error loading[10;24H[32m| [39mshared library libruby.so.2.7: No such file or[11;24H[32m| [39mdirectory (needed by /usr/lib/weechat/plugins/ruby.so)[12;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C plugin,[13;24H[32m| [39mtry command to load scripts (/perl, /python, ...)[14;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin[15;24H[32m| [39m"/usr/lib/weechat/plugins/spell.so": Error loading[16;24H[32m| [39mshared library libaspell.so.15: No such file or[17;24H[32m| [39mdirectory (needed by /usr/lib/weechat/plugins/spell.so)[18;11H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C plugin,[19;24H[32m| [39mtry command to load scripts (/perl, /python, ...)[20;11H06[33m:[39m31[33m:[39m28 [32m| [39mPlugins loaded: alias, buflist, charset, exec, fifo,[21;24H[32m| [39mfset, irc, logger, perl, python, relay, script,[22;24H[32m| [39mtrigger, xfer

[m[24;11H[1;11H[44mWeeChat 2.9 (C) 2003-2020 - https://weechat.org/[24;11H[49m[mM[C[44m06:31[36m[44m][39;49m[44m [36m[44m[[39;49m[44m1[36m[44m][39;49m[44m [36m[44m[[39;49m[44mcore[36m[44m][39;49m[44m [93m[44m1[36m[44m:[97m[44mweechat[24;11H[39;49m[m[H [34m│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│
│[24;11H[39m[m[2;3H06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin "/usr/lib/weechat/plugins/lua.so":[3;10H[m [32m| [39mError loading shared library liblua.so.5: No such file or[m[K[4;10H [32m| [39mdirectory (needed by /usr/lib/weechat/plugins/lua.so)[m[K
[3G06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C plugin, try[6;10H[m [32m| [39mcommand to load scripts (/perl, /python, ...)[m[K
[3G06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin[m[K[8;10H [32m| [39m"/usr/lib/weechat/plugins/ruby.so": Error loading shared[9;10H[m [32m| [39mlibrary libruby.so.2.7: No such file or directory (needed by[10;10H[m [32m| [39m/usr/lib/weechat/plugins/ruby.so)[m[K
[3G06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C [70G, try[m[K[12;10H [32m| [39mcommand to load scripts (/perl, /python, ...)[m[K
[3G06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mError: unable to load plugin[m[K[14;10H [32m| [39m"/usr/lib/weechat/plugins/spell.so": Error loading shared[15;10H[m [32m| [39mlibrary libaspell.so.15: No such file or directory (needed by[16;10H[m [32m| [39m/usr/lib/weechat/plugins/spell.so)[m[K
[3G06[33m:[39m31[33m:[39m28 [93m=!=[39m [32m| [39mIf you're trying to load a script and not a C [70G, try[m[K[18;10H [32m| [39mcommand to load scripts (/perl, /python, ...)[m[K
[3G06[33m:[39m31[33m:[39m28 [32m| [39mPlugins loaded: alias, buflist, charset, exec, fifo, fset, irc,[20;10H[m [32m| [39mlogger, perl, python, relay, script, trigger, xfer[m[K
[3G06[33m:[39m31[33m:[39m28 [32m| [39mfifo: pipe closed[m[K
[3G06[33m:[39m31[33m:[39m28 [32m| [39mPlugins unloaded[m[K[24;11H [3G[m[1d[44mWeeChat 2.9 (C) 2003-2020 - https://weechat.org/ [24;3H[49m[mM[36m[44m[[39;49m[44m06:31[36m[44m][39;49m[44m [36m[44m[[39;49m[44m1[36m[44m][39;49m[44m [36m[44m[[39;49m[44mcore[36m[44m][39;49m[44m [93m[44m1[36m[44m:[97m[44mweechat[39;49m[44m
</details>

**Comment by A75G** [comment]
Okay fix coming up.
