### ISSUE TITLE
[Request] Subsonic

### ISSUE THREAD

**Issue by dtc-tech** [A75G/docker-templates#21]
* Docker Link: 
[https://hub.docker.com/r/hurricane/subsonic/](https://hub.docker.com/r/hurricane/subsonic)

And/or
* Git Link:
[https://github.com/sindremehus/subsonic](https://github.com/sindremehus/subsonic)

**Comment by A75G** [comment]
> 
> 
>     * Docker Link:
>       [https://hub.docker.com/r/hurricane/subsonic/](https://hub.docker.com/r/hurricane/subsonic)
> 
> 
> And/or
> 
>     * Git Link:
>       https://github.com/sindremehus/subsonic
This docker haven't been updated for awhile cant do 
![image](https://user-images.githubusercontent.com/31223569/85422021-ca6e7f00-b57d-11ea-840b-24731082e70c.png)
