### ISSUE TITLE
[Request] Ubuntu and/or Debian

### ISSUE THREAD

**Issue by sic79** [A75G/docker-templates#29]
# Docker Template Request

**Docker Link:**
 https://hub.docker.com/_/ubuntu
https://hub.docker.com/_/debian
**Git Link:**
https://github.com/docker-library/repo-info/tree/master/repos/ubuntu
https://github.com/docker-library/repo-info/tree/master/repos/debian

### Optional *(This will help alot)*
**Description:**
**Icon (link or attached):**
Ubuntu Icon - https://d1q6f0aelx0por.cloudfront.net/product-logos/library-ubuntu-logo.png?
Debian Icon - https://d1q6f0aelx0por.cloudfront.net/product-logos/library-debian-logo.png?

**Comment by A75G** [comment]
what exactly you want me to do with ubuntu or debian docker?
they are used for other dockers

**Comment by sic79** [comment]
@A75G Hi, I would like to have a "non gui"/headless linux installation you could easily ssh into. It could be used for things as installing various small apps/services for testing or as a everyday install. For example I run weechat on a ubuntu server vm right now and I think that´s a little to much for running small tasks. So I thought it would be awesome to have some sort of minimal but yet powerful linux distro such as debian or ubuntu in a small dockerized environment.

Do you think that would be doable?

**Comment by A75G** [comment]
I dont think i can do that if im being honest.
Btw i tried weechat template before had problem but i usually try again you never know what i miss.

**Comment by sic79** [comment]
Ah ok, well it was worth asking :).
I see, do not spend to much time on troubleshooting if you can´t get it running. I have no idea how many ppl use it of unraid users besides me, but I can definitely recommend it as a IRC client.

Thanks for looking into my "issues" :)
