### ISSUE TITLE
[BUG] - FreePBX -  Can't seem to locate /usr/sbin/fwconsole.. Exitting

### ISSUE THREAD

**Issue by jaburges** [A75G/docker-templates#30]
**Describe the bug**
On install (seems like a common issue) 
```Can't seem to locate /usr/sbin/fwconsole.. Exitting```
https://github.com/tiredofit/docker-freepbx/issues/77
https://github.com/tiredofit/docker-freepbx/issues/120
https://github.com/tiredofit/docker-freepbx/issues/109

**To Reproduce**
1. install separate MySQL docker
2. Configure Docker and install
3. Set `DEBUG_MODE=TRUE`

**Expected behavior**
Install should download various modules etc.

**Additional context**
NOTE - the comments state "Don't use embedded database cant get it to work"
However I tried it as the other method didnt work, and it does work using the internal DB

Steps
1. Set `DB_EMBEDDED=TRUE`
2. remove DB related environment variables
   DB_NAME
   DB_HOST
   DB_USER
   DB_PASSWORD
3. ensure db volume is set
4. wait for install to complete 

Figured the last part was more interesting than the fact it wasnt working?

**Comment by bucky2780** [comment]
i am also seeing this behaviour... cannot get this to install using existing mariadb docker.

>>
[100m[NOTICE][49m ** [freepbx] Setting file permissions
[42m[INFO][49m ** [freepbx] New install detected - please wait while we fetch FreePBX - will take up to 30 minutes!
[100m[NOTICE][49m ** [freepbx] Starting Asterisk 17.6.0 for the first time
[100m[NOTICE][49m ** [freepbx] Installing FreePBX 15.0.16.56 source code
[101m[ERROR][49m ** [freepbx] Can't seem to locate /usr/sbin/fwconsole.. exiting
[cont-init.d] 10-freepbx: exited 1.
[cont-init.d] 15-socat: executing...
[cont-init.d] 15-socat: exited 0.
[cont-init.d] 99-container: executing...
**********************************************************************************************************************
**********************************************************************************************************************
**** ****
**** ERROR - Some initialization scripts haven't completed - All services are now halted ****
**** - The following scripts in '/etc/cont-init.d' did not pass their completion check ****
**** ****
**********************************************************************************************************************
**********************************************************************************************************************

**Comment by jaburges** [comment]
Did you try enabling the embedded_DB?
That got me going.

**Comment by bucky2780** [comment]
no, because its not really what I wanted. I will try with VM in the interim until the docker comes good.

**Comment by disruptivepatternmaterial** [comment]
Any updates on this issue? How can I help...has been dead in the water. I am using embedded true.

**Comment by A75G** [comment]
> Any updates on this issue? How can I help...has been dead in the water. I am using embedded true.

I'll try to make it work soon.
Been busy with work this couple of months .

**Comment by A75G** [comment]
I updated the template with embedd db hopefully its fixed now
