### ISSUE TITLE
[Request] Visionect Software Suite

### ISSUE THREAD

**Issue by kfoxton** [A75G/docker-templates#31]
# Docker Template Request

**Docker Link:**https://support.getjoan.com/hc/en-us/articles/360008822260-How-to-install-the-Visionect-Software-Suite-without-the-VM
**Git Link:**

### Optional *(This will help alot)*
**Description:** Used for the Free on-premise version of the Joan Meeting application and displays.
**Icon (link or attached):**https://getjoan.com/wp-content/themes/Divi-child/img/redesign/brand/logo-joan.svg

**Comment by A75G** [comment]
Can't do too much complication.
