### ISSUE TITLE
[BUG] Pterodactyl Daemon

### ISSUE THREAD

**Issue by tom1422** [A75G/docker-templates#33]
**Describe the bug**
Upon starting a Pterodactyl server, I recieve an error in logs telling me that I am trying to mount a directory onto a file.

**To Reproduce**
Here's Everything I've done so far:
- Install Pterodactyl Web server and connect it to an existing mysql database
- Add the desired user and login
- Create the config with the local ip address
- Copy the config into a config.yml file
- Install Pterodactyl daemon
- Add a new path mapping from /etc/pterodactyl to the config file on the unraid server appdata folder
- Run pterodactyl daemon for the first time
- Stop pterodactyl daemon
- Edit the config file and change the interface IP, gateway etc
- Add a 1 to 1 path mapping to /mnt/user/appdata/pterodactyl/daemon/data/ on both sides
- Edit the config file for data, archive_directory and backup_directory to /mnt/user/appdata/pterodactyl/daemon/data/ with volumes, archives and backups on the end of each
- Start up pterodactyl-daemon
- Create new Port allocations on the web panel with the same ip as the unraid server because anything else gives a failed to bind message
- Create a new server with the port allocations you just made
- Start this server
- Get this error message: `an error was encountered processing an event error=Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/timezone\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/a1f09473a7d7f814f2890eb850d01ce268f72c1a8047bf5c2acc563e67c7d776\\\" at \\\"/var/lib/docker/btrfs/subvolumes/a1f09473a7d7f814f2890eb850d01ce268f72c1a8047bf5c2acc563e67c7d776/etc/timezone\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type error_identifier=d7fb26d7-96c0-479e-9d2a-418106f826d3 event=set state server=a3de539d-e96c-431c-997e-a347c031b076`

**Expected behavior**
For the container to start.

**Additional context**
Please tell me if I installed it correctly as I probably haven't but I couldn't find anthing on the internet with my issue and found no guides to install pterodactyl on unraid. Also, if i get this working is there any way to get allocations to no use the unraid ip and instead one on a different interface. Not really sure if this is a bug but the template seemed more fitting. Thanks for any help you can give me.

**Comment by A75G** [comment]
I updated the deamon today did you try that?

**Comment by tom1422** [comment]
Thanks for your quick response, I installed it about an hour ago and I noticed the change this morning from yesterday so I believe i am on the right version. Could it be an issue with how i installed it?

**Comment by tom1422** [comment]
It worked when I removed the time flag below:
<img width="715" alt="timeflag" src="https://user-images.githubusercontent.com/60324543/97216820-4bed4c80-17be-11eb-8f1a-50cf6dfddc7d.PNG">
If I did `cat` on each of the folders in the error message and heres what i found:
 - /etc/timezone - Returns `read error: Is a directory` - Mounted by the unraid docker and when removed it worked fine
 - /var/lib/docker/btrfs/subvolumes/a1f09473a7d7f814f2890eb850d01ce268f72c1a8047bf5c2acc563e67c7d776/etc/timezone - This is a file - returns `Etc/UTC`

I hope this info helps. Not sure how necessary the Time thingy is but i have removed it for now.

**Comment by A75G** [comment]
Thank you for help, i totally missed that i removed Time for time being.
