### ISSUE TITLE
[BUG] - Pterodactyl Daemon - Can't configure

### ISSUE THREAD

**Issue by finn119** [A75G/docker-templates#38]
**Describe the bug**
I have installed the docker containers for the Pterodactyl Panel and Daemon from the Community Applications plugin in **Unraid**. I left all the settings on default. When I try to configure the daemon by using the "Auto Deploy" option, or by placing the configuration file. The daemon then tries to initialize.
After a few seconds the docker container crashes and it throws this error in the unraid docker logs:
`FATAL: [Nov 10 19:30:24.747] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space`
You can see the complete log in the screenshot below.

**To Reproduce**
1. Install the Pterodactyl Panel and Daemon docker container through the Community Applications plugin
2. Start both docker containers
3. Configure in the panel a node and location
4. Copy the daemon configuration from the panel(This can be done by the "Auto Deploy" option, or by placing the configuration file in the daemon.

**Expected behavior**
That the daemon connects with the panel and it is possible to create servers

**Screenshots**
[https://i.imgur.com/D4LZ2M9.png](https://i.imgur.com/D4LZ2M9.png)
Look at the fatal error

**Additional context**
I have already tried several things, like making a custom network for both docker containers and changing the port numbers.
I think you can ignore the above warning about the time zone.

**Comment by A75G** [comment]
> 
> 
> **Describe the bug**
> I have installed the docker containers for the Pterodactyl Panel and Daemon from the Community Applications plugin in **Unraid**. I left all the settings on default. When I try to configure the daemon by using the "Auto Deploy" option, or by placing the configuration file. The daemon then tries to initialize.
> After a few seconds the docker container crashes and it throws this error in the unraid docker logs:
> `FATAL: [Nov 10 19:30:24.747] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space`
> You can see the complete log in the screenshot below.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Install the Pterodactyl Panel and Daemon docker container through the Community Applications plugin
> 
>     2. Start both docker containers
> 
>     3. Configure in the panel a node and location
> 
>     4. Copy the daemon configuration from the panel(This can be done by the "Auto Deploy" option, or by placing the configuration file in the daemon.
> 
> 
> **Expected behavior**
> That the daemon connects with the panel and it is possible to create servers
> 
> **Screenshots**
> https://i.imgur.com/D4LZ2M9.png
> Look at the fatal error
> 
> **Additional context**
> I have already tried several things, like making a custom network for both docker containers and changing the port numbers.
> I think you can ignore the above warning about the time zone.

can you test chaning panel tag from :latest to :v0.7.18

**Comment by finn119** [comment]
> > **Describe the bug**
> > I have installed the docker containers for the Pterodactyl Panel and Daemon from the Community Applications plugin in **Unraid**. I left all the settings on default. When I try to configure the daemon by using the "Auto Deploy" option, or by placing the configuration file. The daemon then tries to initialize.
> > After a few seconds the docker container crashes and it throws this error in the unraid docker logs:
> > `FATAL: [Nov 10 19:30:24.747] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space`
> > You can see the complete log in the screenshot below.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > ```
> > 1. Install the Pterodactyl Panel and Daemon docker container through the Community Applications plugin
> > 
> > 2. Start both docker containers
> > 
> > 3. Configure in the panel a node and location
> > 
> > 4. Copy the daemon configuration from the panel(This can be done by the "Auto Deploy" option, or by placing the configuration file in the daemon.
> > ```
> > 
> > 
> > **Expected behavior**
> > That the daemon connects with the panel and it is possible to create servers
> > **Screenshots**
> > https://i.imgur.com/D4LZ2M9.png
> > Look at the fatal error
> > **Additional context**
> > I have already tried several things, like making a custom network for both docker containers and changing the port numbers.
> > I think you can ignore the above warning about the time zone.
> 
> can you test chaning panel tag from :latest to :v0.7.18

When I do this, I'm not able to configure the daemon with the Configuration File from the panel. I think the daemon looks for a .yml and the panel creates a .json file.

**Comment by A75G** [comment]
If im not mistaken the new panel only support the new Wings software so daemon wont work
That why i suggested going back to 0.7
![image](https://user-images.githubusercontent.com/31223569/98840944-80b50100-2458-11eb-84cf-62d16a1b7c63.png)

**Comment by finn119** [comment]
Okay, but what version do I have to use in the daemon tag?

**Comment by finn119** [comment]
I have done some research today myself. I installed the Panel version: v0.7.18 and the Daemon version: v0.6.13. I tried to configure everything, but in the end I got the same error (I added the screenschot below).
So I think it isn't a problem with Pterodactyl, but with Unraid or Docker.

![chrome_2020-11-12_21-25-23](https://user-images.githubusercontent.com/37500230/98992557-a19b5600-252d-11eb-936f-0bbf2abc2004.png)

**Comment by A75G** [comment]
"Pool overlaps with other one on this address space"
Can you give Daemon it own ip and try to add it in the Panel?

**Comment by finn119** [comment]
Unfortunately it doesn't work. I've added the logs and configuration with screenshots.
![chrome_2020-11-14_00-20-52](https://user-images.githubusercontent.com/37500230/99129957-4d68a280-260f-11eb-9262-7edea5ed152f.png)

![chrome_2020-11-14_00-20-38](https://user-images.githubusercontent.com/37500230/99129959-4e013900-260f-11eb-85c7-e5b51c3a10c4.png)

**Comment by finn119** [comment]
> Unfortunately it doesn't work. I've added the logs and configuration with screenshots.
> ![chrome_2020-11-14_00-20-52](https://user-images.githubusercontent.com/37500230/99129957-4d68a280-260f-11eb-9262-7edea5ed152f.png)
> 
> ![chrome_2020-11-14_00-20-38](https://user-images.githubusercontent.com/37500230/99129959-4e013900-260f-11eb-85c7-e5b51c3a10c4.png)

I've also made sure the ip isn't being used by anything else than the docker container.

**Comment by A75G** [comment]
I'm removing pterodactyl-daemon until i can get it to work

**Comment by Frooodle** [comment]
I got this issue today with latest offical dockers in unraid

**Comment by A75G** [comment]
> 

This docker template has been removed for sometime please check other template.
