### ISSUE TITLE
[BUG] Cannot get it to run. Period. 

### ISSUE THREAD

**Issue by PRTNaus** [A75G/docker-templates#39]
**Describe the bug**
I am unable to get the docker to run successfully however I may just be dumb.

**To Reproduce**
1. Installed the Daemon and Panel dockers 
2. Configured the panel to look for my docker MySQL server with the remade pterodactyl database, using root as the user with the password. Didn't touch the Daemon.
3. Started panels
4. Cannot access Panel via IP
5. Daemon and Panel produce there attached logs (images)

**Screenshots**
<img width="1012" alt="Screen Shot 2020-11-22 at 5 32 38 pm" src="https://user-images.githubusercontent.com/42082250/99896917-2124e400-2ce9-11eb-96e3-229e4b103c7d.png">
<img width="1012" alt="Screen Shot 2020-11-22 at 5 32 45 pm" src="https://user-images.githubusercontent.com/42082250/99896923-26822e80-2ce9-11eb-90d6-56fb60e1f0b7.png">

**Comment by A75G** [comment]
I'm removing pterodactyl-daemon until i can get it to work

**Comment by PRTNaus** [comment]
> I'm removing pterodactyl-daemon until i can get it to work

Daemon is outdated, need to implement Wings. Tried getting it to work but I'm not a huge linux guy. Can get the Panel working just fine. However the Daemon is not updated for panel v1+ as the configuration file is different.

**Comment by joeydoesthings** [comment]
> > I'm removing pterodactyl-daemon until i can get it to work
> 
> Daemon is outdated, need to implement Wings. Tried getting it to work but I'm not a huge linux guy. Can get the Panel working just fine. However the Daemon is not updated for panel v1+ as the configuration file is different.

Also hoping and waiting for a wings (v1)  docker template
