### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tenebras50** [A75G/docker-templates#40]
**Describe the bug**
does not start  correctly

**To Reproduce**
pull nikisweeting/archivebox:latest
start it on unraid, 
**Expected behavior**
a working program

errors:

in/archive: No such file or directory
rchivebox [--help] [--version]

ersion,init,config,add,remove,update,list,status,shell,manage,server,oneshot,schedule}]

ox: error: argument subcommand: invalid choice: 'bash' (choose from 'help', 'version', 'init', 'config', 'add', 'remove', 'update', 'list', 'status', 'shell', 'manage', 'server', 'oneshot', 'schedule')

**Comment by A75G** [comment]
please look at the notes https://github.com/A75G/docker-templates/blob/master/README.md#first-installation
