### ISSUE TITLE
[BUG] The moodle template needs a volume mapping to /bitnami/moodledata

### ISSUE THREAD

**Issue by masteryodha** [A75G/docker-templates#42]
**Describe the bug**
Everytimes I update the container or when I change a variable in the docker template, the container doesn't work after that.  I get a 503 error.

When that happens, I need to go into the docker and changer permission to the /bitnami/moodledata manually to daemon:daemon.

I debugged the problem on the github for bitnami:moodle (https://github.com/bitnami/bitnami-docker-moodle/issues/161) and he find out  that I needed the volume mapping to bitnami/moodledata.  When I did this, everything is working perfectly.

**To Reproduce**
1- install moodle docker
2- Check if container works : ok
3- Changer variable value or add new variable in docoker
4- Container doesn't work anymore : url shows : Invalid permissions detected when trying to create a directory

**Expected behavior**
I should not have this error after changing a variable, adding a variable or updating the container.

**Screenshots**

**Additional context**
See the issue : https://github.com/bitnami/bitnami-docker-moodle/issues/161 where we investigate the bug and found the solution.

Thank you

**Comment by A75G** [comment]
I have added volume mapping to bitnami/moodledata to the template.
Thank you for investigiting this issue.

**Comment by masteryodha** [comment]
No problem.  I want to learn about docker and such.  So I try to learn investigating bugs and how everything works.

I'll close the ticket.

Next time, I'll try to make a Pull request

**Comment by A75G** [comment]
im reopening this issue because im having difficulty testing moodle 
could you please send me the working template you have with /bitnami/moodledata?

**Comment by A75G** [comment]
ignore last comment it was my testing database.
