### ISSUE TITLE
[Request] Blue Iris

### ISSUE THREAD

**Issue by sic79** [A75G/docker-templates#43]
# Docker Template Request

Docker Link: https://hub.docker.com/r/jshridha/blueiris/
Git Link: https://github.com/jshridha/docker-blueiris

### Optional *(This will help alot)*
Description:Blue Iris video security software runs on a PC and can provide recording and playback for up to 64 IP network cameras or webcams.  Blue Iris is affordable and powerful enough to safeguard your family, property and valuables at home or work.
Icon (link or attached): https://d36jcksde1wxzq.cloudfront.net/be7833db9bddb4494d2a7c3dd659199a.png

**Comment by A75G** [comment]
https://github.com/A75G/docker-templates/commit/6cde588db533ab395374a93877f22bff681a9a2e
