### ISSUE TITLE
[Request] Mediathekview Docker Application

### ISSUE THREAD

**Issue by Goeste** [A75G/docker-templates#44]
# Docker Template Request

https://hub.docker.com/r/tuxflo/docker-mediathekview/
https://github.com/tuxflo/docker-mediathekview

### Optional *(This will help alot)*
Using this container allows you to run Mediathekview as a Service and control it via webbrowser like firefox or chrome. The x11rdp feature is copied from https://github.com/sparklyballs/desktop-dockers. I'm running this on a NAS to add Videos out of the Mediathek directly to my Multimedia Collection.

https://de.wikipedia.org/wiki/MediathekView#/media/Datei:MediathekView_Logo_2017.svg

**Comment by A75G** [comment]
I'm closing this request as im stopping doing requests.
