### ISSUE TITLE
LibrePhotos [Request]

### ISSUE THREAD

**Issue by kfoxton** [A75G/docker-templates#45]
# Docker Template Request

**Docker Link:**https://github.com/LibrePhotos/librephotos#docker-compose-method-recommended
**Git Link:https://github.com/LibrePhotos/librephotos

### Optional *(This will help alot)*
**Description:**LibrePhotos is a fork of Ownphotos
**Icon (link or attached):**

**Comment by A75G** [comment]
I'm closing this request as im stopping doing requests.
