### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by asparagus1564** [A75G/docker-templates#46]
# Docker Template Request

Ddns-route53
I can’t seem to locate the config.yaml template. I’m happy to help if I can, but I know nothing about how they relate. I have it running in regular docker, but am hoping to have everything in unraid docker. 

Thanks in advance!

**Comment by A75G** [comment]
https://github.com/A75G/docker-templates/commit/e1587b7997777a5b2926ca945422e363f72003e3

**Comment by asparagus1564** [comment]
Updated and THANK YOU!
