### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CyBuzz** [A75G/docker-templates#48]
**Describe the bug**
Linkding application will not start

**To Reproduce**
1. Go to docker page in Unraid
2. Click on linkding icon
3. Select webui and new window opens with error unable to load
4. View logs and see error repeated
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:8015 client_addr: 192.168.1.219 client_port: 17608] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]

**Expected behavior**
Linkding login page displays

**Screenshots**

**Additional context**

**Comment by A75G** [comment]
Can you remove the docker with image and appdata, then reinstall it because i cant see any problem when i just installed it.
Have you changed any settings on the template? if yes please leave it as default.

**Comment by CyBuzz** [comment]
I removed the docker, the image and deleted the app data directory. I didnt change any settings. I installed, created a super user per instructions and restarted the docker. I get the same message.

This was the only thing i could find on google to try but i cant figure out how to edit the config.
https://stackoverflow.com/questions/50189365/uwsgi-error-hr-instance-read-connection-reset-by-peer ***@***.***/0?redirect=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F50189365%2Fuwsgi-error-hr-instance-read-connection-reset-by-peer&recipient=cmVwbHkrQUlSV1hBVEE2SVVJUjZTQVFBM1kySkY2UEtFT1ZFVkJOSEhERlY3RDZNQHJlcGx5LmdpdGh1Yi5jb20%3D)
and then i read this....
https://github.com/unbit/uwsgi/issues/1831 ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Funbit%2Fuwsgi%2Fissues%2F1831&recipient=cmVwbHkrQUlSV1hBVEE2SVVJUjZTQVFBM1kySkY2UEtFT1ZFVkJOSEhERlY3RDZNQHJlcGx5LmdpdGh1Yi5jb20%3D)
reading that i saw they they were having an issue and it was browser specific....i was using Firefox. i switched to edge to test....and it worked. I will keep experimenting since i dont use edge.
In case it helps, below is my log.
Operations to perform:
Apply all migrations: admin, auth, authtoken, bookmarks, contenttypes, sessions
Running migrations:
Applying contenttypes.0001_initial... OK
Applying auth.0001_initial... OK
Applying admin.0001_initial... OK
Applying admin.0002_logentry_remove_auto_add... OK
Applying admin.0003_logentry_add_action_flag_choices... OK
Applying contenttypes.0002_remove_content_type_name... OK
Applying auth.0002_alter_permission_name_max_length... OK
Applying auth.0003_alter_user_email_max_length... OK
Applying auth.0004_alter_user_username_opts... OK
Applying auth.0005_alter_user_last_login_null... OK
Applying auth.0006_require_contenttypes_0002... OK
Applying auth.0007_alter_validators_add_error_messages... OK
Applying auth.0008_alter_user_username_max_length... OK
Applying auth.0009_alter_user_last_name_max_length... OK
Applying auth.0010_alter_group_name_max_length... OK
Applying auth.0011_update_proxy_permissions... OK
Applying authtoken.0001_initial... OK
Applying authtoken.0002_auto_20160226_1747... OK
Applying bookmarks.0001_initial... OK
Applying bookmarks.0002_auto_20190629_2303... OK
Applying bookmarks.0003_auto_20200913_0656... OK
Applying bookmarks.0004_auto_20200926_1028... OK
Applying bookmarks.0005_auto_20210103_1212... OK
Applying bookmarks.0006_bookmark_is_archived... OK
Applying bookmarks.0007_userprofile... OK
Applying bookmarks.0008_userprofile_bookmark_date_display... OK
Applying sessions.0001_initial... OK
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static
*** Starting uWSGI 2.0.18 (64bit) on [Thu Apr 8 08:04:36 2021] ***
compiled with version: 8.3.0 on 06 April 2021 21:41:58
os: Linux-5.10.21-Unraid #1 SMP Sun Mar 7 13:39:02 PST 2021
nodename: 214547b4dbd6
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /etc/linkding
writing pidfile to /tmp/linkding.pid
detected binary path: /opt/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
chdir() to /etc/linkding
your processes number limit is 30770
your memory page size is 4096 bytes
detected max file descriptor number: 40960
building mime-types dictionary from file /etc/mime.types...565 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36111 (port auto-assigned) fd 3
Python version: 3.9.4 (default, Apr 5 2021, 18:26:27) [GCC 8.3.0]
Python main interpreter initialized at 0x5583d32ebde0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5583d32ebde0 pid: 11 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 12, cores: 2)
spawned uWSGI worker 2 (pid: 14, cores: 2)
spawned uWSGI worker 3 (pid: 15, cores: 2)
spawned uWSGI worker 4 (pid: 17, cores: 2)
*** Stats server enabled on 127.0.0.1:9191 fd: 18 ***
spawned uWSGI http 1 (pid: 20)
Operations to perform:
Apply all migrations: admin, auth, authtoken, bookmarks, contenttypes, sessions
Running migrations:
No migrations to apply.
There is already a secret key in `secretkey.txt`
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static
*** Starting uWSGI 2.0.18 (64bit) on [Thu Apr 8 08:06:04 2021] ***
compiled with version: 8.3.0 on 06 April 2021 21:41:58
os: Linux-5.10.21-Unraid #1 SMP Sun Mar 7 13:39:02 PST 2021
nodename: 214547b4dbd6
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /etc/linkding
writing pidfile to /tmp/linkding.pid
detected binary path: /opt/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
chdir() to /etc/linkding
your processes number limit is 30770
your memory page size is 4096 bytes
detected max file descriptor number: 40960
building mime-types dictionary from file /etc/mime.types...565 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:42345 (port auto-assigned) fd 3
Python version: 3.9.4 (default, Apr 5 2021, 18:26:27) [GCC 8.3.0]
Python main interpreter initialized at 0x55be09fccde0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55be09fccde0 pid: 10 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 11, cores: 2)
spawned uWSGI worker 2 (pid: 13, cores: 2)
spawned uWSGI worker 3 (pid: 14, cores: 2)
spawned uWSGI worker 4 (pid: 16, cores: 2)
*** Stats server enabled on 127.0.0.1:9191 fd: 18 ***
spawned uWSGI http 1 (pid: 19)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55be09fccde0 pid: 10 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 11, cores: 2)
spawned uWSGI worker 2 (pid: 13, cores: 2)
spawned uWSGI worker 3 (pid: 14, cores: 2)
spawned uWSGI worker 4 (pid: 16, cores: 2)
*** Stats server enabled on 127.0.0.1:9191 fd: 18 ***
spawned uWSGI http 1 (pid: 19)
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 43994] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 44250] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 44506] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 44762] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 45018] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 45274] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 45530] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 45786] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 46042] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
invalid request block size: 4834 (max 4096)...skip
[uwsgi-http key: 192.168.1.189:9090 client_addr: 192.168.1.219 client_port: 46298] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
