### ISSUE TITLE
[Request] Snipe-IT

### ISSUE THREAD

**Issue by kfoxton** [A75G/docker-templates#5]
* Docker Link: https://hub.docker.com/r/snipe/snipe-it/

And/or

* Git Link: https://github.com/snipe/snipe-it

**Comment by A75G** [comment]
I tried official couldn't get it to run
So i made docker template for Snip-it linuxserver repo
hopefully waiting for approval on there pull request
https://github.com/linuxserver/docker-templates/pull/195

**Comment by kfoxton** [comment]
Thanks.

**Comment by A75G** [comment]
has been added by linuxserver.io
