### ISSUE TITLE
[BUG] archivebox complains it should never be run as root

### ISSUE THREAD

**Issue by erickguan** [A75G/docker-templates#50]
**Describe the bug**
When I try to run `archivebox manage createsuperuser` in the container to set up an admin user, archivebox complains 
```
root@afa7f86cb3c1:/data# archivebox manage createsuperuser
[i] [2021-07-19 21:18:30] ArchiveBox v0.6.2: archivebox manage createsuperuser
    > /data

[!] ArchiveBox should never be run as root!
    For more information, see the security overview documentation:
        https://github.com/ArchiveBox/ArchiveBox/wiki/Security-Overview#do-not-run-as-root

```

**To Reproduce**
1. Go to console from docker dashboard in Unraid
2. Right click on console
3. type `archivebox manage createsuperuser` i

**Expected behavior**
Be prompt to setup admin account

**Comment by A75G** [comment]
Please follow this: https://github.com/A75G/docker-templates/blob/master/README.md#first-installation
```
su - archivebox 
cd /data 
archivebox init 
archivebox manage createsuperuser
```
