### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by jimminycreeket** [A75G/docker-templates#52]
# Docker Template Request

**Docker Link:** https://hub.docker.com/r/aadl/cups-alpine/
**Git Link:**https://github.com/aadl/docker-cups-alpine

https://www.cups-pdf.de/welcome.shtml

### Optional *(This will help alot)*
**Description:** A virtual CUPS Server to print to PDF. A way to by-pass applications that won't allow you to print to local Virtual Printers
**Icon (link or attached):**
https://adminpick.com/wp-content/uploads/logos/cups-pdf.png
![download](https://user-images.githubusercontent.com/56313318/130697056-f956bfb5-eb63-43af-9aa7-a9e383b206a7.png)

**Comment by A75G** [comment]
I'm closing this request im stopping the request and the last commit was 2018.
