### ISSUE TITLE
BigBlueButton Docker Server [Request]

### ISSUE THREAD

**Issue by usshauler** [A75G/docker-templates#56]
# Docker Template Request

**Docker Link:** https://hub.docker.com/r/bigbluebutton/bigbluebutton
**Git Link:** https://github.com/bigbluebutton/bigbluebutton

### Optional *(This will help alot)*
**Description:** A video and audio conferencing and collaboration server. Can be integrated to self hosted Mattermost server amongst others.
**Icon (link or attached):** https://bigbluebutton.org/

**Comment by A75G** [comment]
I'm closing this request as im stopping doing requests.
