### ISSUE TITLE
[BUG] LibreNMS docker does not automatically discover and periodically poll added devices

### ISSUE THREAD

**Issue by logock** [A75G/docker-templates#57]
**Describe the bug**
The LibreNMS docker does not automatically discover and poll devices.

**To Reproduce**
1. Start docker
2. Add devices and wait for them to be automatically discovered and polled
3. They will not be discovered and polled via cron job

**Expected behavior**
Devices are automatically discovered and polled periodically

**Comment by A75G** [comment]
https://github.com/librenms/docker/issues/129

Check this

**Comment by Topslakr** [comment]
There is nothing in the docker container that is triggering a scheduled run of these tasks, which I assume would normally be handled by cron.

Running scan-snmp.py produces a bumper crop of errors:

/opt/librenms # ./snmp-scan.py
Scanning IPs:
Killed
/opt/librenms # Process ForkPoolWorker-4:
Process ForkPoolWorker-1:
Process ForkPoolWorker-3:
Process ForkPoolWorker-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

The above repeats many times.

But, if I run `lnms device:poll 192.168.16.*` it will scan through all of the devices I have added to the system manually within that /24.
