### ISSUE TITLE
[Request] ecoDMS 21.06 (burns) 

### ISSUE THREAD

**Issue by klauskn** [A75G/docker-templates#58]
# Docker Template Request

[**Docker Link: https://hub.docker.com/r/ecodms/ecodms**]
**Git Link:**
https://www.ecodms.de/index.php/en/download/ecodms-archiv/ecodms-burns/ecodms-build-21-06

### Optional *(This will help alot)*
**Description:**
**Icon (link or attached):**

**Comment by A75G** [comment]
I'm closing this request as im stopping doing requests.
