### ISSUE TITLE
[Request] NetBox

### ISSUE THREAD

**Issue by kfoxton** [A75G/docker-templates#6]
* Docker Link: https://hub.docker.com/r/netboxcommunity/netbox/tags/

And/or

* Git Link: https://github.com/netbox-community/netbox

**Comment by A75G** [comment]
Done

**Comment by kfoxton** [comment]
Application doesn't start? Logs show:
...........................................................;........................................................... and then it shuts down?

**Comment by A75G** [comment]
> 
> 
> Application doesn't start? Logs show:
> ...........................................................�;........................................................... and then it shuts down?

did u make sure posgres config right
