### ISSUE TITLE
[BUG] db-backup MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)

### ISSUE THREAD

**Issue by Gerben-W** [A75G/docker-templates#62]
Since version 2.10.3 the automatic backup no longer working.
Version 2.10.2 still works

When running the backup-now script with debug=TRUE, the message as underneath is showing.

bash-5.1# backup-now 
** Performing Manual Backup
+ PROCESS_NAME=db-backup
+ date
+ '[' NOW '!=' NOW ']'
+ sanity_var DB_TYPE 'Database Type'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:28:50 [DEBUG] /etc/services.available/10-db-backup/run ** [db-backup] Looking for existence of DB_TYPE environment variable
+ '[' '!' -v DB_TYPE ']'
+ output_on
+ '[' TRUE = TRUE ']'
+ set -x
+ sanity_var DB_HOST 'Database Host'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:28:50 [DEBUG] /etc/services.available/10-db-backup/run ** [db-backup] Looking for existence of DB_HOST environment variable
+ '[' '!' -v DB_HOST ']'
+ output_on
+ '[' TRUE = TRUE ']'
+ set -x
+ dbtype=mysql
+ case "$dbtype" in
+ dbtype=mysql
+ dbport=3306
+ [[ -n PASSWORD ]]
+ file_env DB_PASS
+ '[' TRUE = TRUE ']'
+ local var=DB_PASS
+ local fileVar=DB_PASS_FILE
+ local def=
+ local val=
+ '[' '' ']'
+ '[' PASSWORD ']'
+ val=PASSWORD
+ '[' -z PASSWORD ']'
+ export DB_PASS=PASSWORD
+ DB_PASS=PASSWORD
+ unset DB_PASS_FILE
+ BACKUP_LOCATION=FILESYSTEM
+ COMPRESSION=GZ
+ COMPRESSION_LEVEL=3
+ DB_DUMP_BEGIN=2300
+ DB_DUMP_FREQ=1440
+ DB_DUMP_TARGET=/backup
+ dbhost=192.168.1.100
+ dbname=
+ dbpass=PASSWORD
+ dbuser=root
+ MD5=TRUE
+ PARALLEL_COMPRESSION=TRUE
+ SIZE_VALUE=bytes
+ SPLIT_DB=TRUE
+ tmpdir=/tmp/backups
+ '[' '' = S3 ']'
+ '[' '' = s3 ']'
+ '[' '' = MINIO ']'
+ '[' '' = minio ']'
+ '[' NOW = NOW ']'
+ DB_DUMP_BEGIN=+0
+ MANUAL=TRUE
+ var_true TRUE
+ '[' TRUE = TRUE ']'
+ bzip='pbzip2 -3'
+ gzip='pigz -3'
+ xzip='pixz -3'
+ zstd='zstd --rm -3'
+ case "$dbtype" in
+ [[ -n PASSWORD ]]
+ export MYSQL_PWD=PASSWORD
+ MYSQL_PWD=PASSWORD
++ date
+ print_debug 'Backup routines Initialized on Sun Jan 16 12:28:50 CET 2022'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:28:50 [DEBUG] /etc/services.available/10-db-backup/run ** [db-backup] Backup routines Initialized on Sun Jan 16 12:28:50 CET 2022
+ '[' NOW '!=' NOW ']'
+ true
+ mkdir -p /tmp/backups
++ date +%Y%m%d-%H%M%S
+ now=20220116-122850
++ date +%H:%M:%S
+ now_time=12:28:50
++ date +%Y-%m-%d
+ now_date=2022-01-16
+ target=mysql__192.168.1.100_20220116-122850.sql
+ case "$dbtype" in
+ check_availability
+ case "$dbtype" in
+ COUNTER=0
+ export MYSQL_PWD=PASSWORD
+ MYSQL_PWD=PASSWORD
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\'''\'' is not accessible, retrying.. ( seconds so far)'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:28:55 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\'''\'' is not accessible, retrying.. ( seconds so far)'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:29:00 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\'''\'' is not accessible, retrying.. ( seconds so far)'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:29:05 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\'''\'' is not accessible, retrying.. ( seconds so far)'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:29:10 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\'''\'' is not accessible, retrying.. ( seconds so far)'
+ output_off
+ '[' TRUE = TRUE ']'
+ set +x
2022-01-16-12:29:15 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server '' is not accessible, retrying.. ( seconds so far)
+ mysql -uroot -P3306 -h192.168.1.100 -e 'SHOW GRANTS FOR CURRENT_USER;'
+ grep -E 'GRANT ALL PRIVILEGES ON ``'
+ sleep 5

**To Reproduce**
1. Login in to the docker
2. Run backup-now command

**Expected behavior**
Backup written

**Comment by A75G** [comment]
change the tag from latest to 2.10.2
