### ISSUE TITLE
[BUG] airsonic-advanced volume mapping Podcast Path should use container path /var/podcasts not /var/podcast

### ISSUE THREAD

**Issue by benfishbus** [A75G/docker-templates#69]
**Describe the bug**
The airsonic-advanced template's container path for Podcast Path does not match what airsonic is looking for out of the box. The template points to `/var/podcast`, while airsonic wants `/var/podcasts` (plural), resulting in an error when airsonic tries to update subscribed podcasts.

**Comment by A75G** [comment]
updated template
