### ISSUE TITLE
[BUG] matrix container - default permissions issues

### ISSUE THREAD

**Issue by tylerstraub** [A75G/docker-templates#77]
Greetings. I am going through the process of attempting a Matrix Synapse implementation using the A75G Docker package on the Unraid platform.

The first thing I have noticed is that there seems to be some sort of permissions issue happening out of box with the `/data` volume mapping. 

I'm going through the process of troubleshooting it now myself and haven't solved it just yet. But I wanted to report what I'm seeing here in case the maintainer wants to try to adjust the package or add some additional setup instructions. 

Thank you!

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 747, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "/usr/lib/python3.11/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/homeserver.log'
```

**Comment by tylerstraub** [comment]
Here was how I resolved the issue:

Made sure that the folder ownership was correct (I'm not sure if this step was necessary): 
`chown -R 991:991 /mnt/user/appdata/matrix`

Edited my `log.config` file that matrix autogenerated in the `/data` volume and changed the path of the `homeserver.log` file to go inside of `/data`:

ex

```
        filename: /data/homeserver.log     
```

Restarted the Docker container, this resolved my issue. I think the following Github issue has some relevant data as to how this may have occurred: https://github.com/matrix-org/synapse/issues/9970

Hope this helps!

**Comment by vaparetia** [comment]
` chown -R 991:991 /mnt/user/appdata/matrix`

This solved my issue as well. No files were being generated for me to edit until the permissions issue was resolved. Thanks for posting.

**Comment by A75G** [comment]
added to template as requirement
