### ISSUE TITLE
[BUG] shlink-web-client GUI port

### ISSUE THREAD

**Issue by pablodre** [A75G/docker-templates#80]
**Describe the bug**
Now, the default port for the GUI is 8080 in the docker container(80 don't work anymore)

**To Reproduce**
Deploy the actual template in Unraid and try open the GUI and get a "Connection refused"

**Expected behavior**
Open the GUI in the mapped port

**Additional context**
https://github.com/shlinkio/shlink-web-client/issues/1052#issuecomment-1922397908
I try to open a PR with the suggestion changes but i don't have permissions.
Best regards

**Comment by A75G** [comment]
https://github.com/A75G/docker-templates/commit/2183c0b33e873f8af7066f132cb455ac2fc757a4

Is this correct only the port changes?

**Comment by A75G** [comment]
I see now there is new additional env (SHLINK_SERVER_URL, SHLINK_SERVER_API_KEY) which simplify the deployment don't know if it better to be included 
`docker run \
    --name shlink-web-client \
    -p 8000:8080 \
    -e SHLINK_SERVER_URL=https://s.test \
    -e SHLINK_SERVER_API_KEY=6aeb82c6-e275-4538-a747-31f9abfba63c \
    shlinkio/shlink-web-client`

**Comment by pablodre** [comment]
> I see now there is new additional env (SHLINK_SERVER_URL, SHLINK_SERVER_API_KEY) which simplify the deployment don't know if it better to be included `docker run \ --name shlink-web-client \ -p 8000:8080 \ -e SHLINK_SERVER_URL=https://s.test \ -e SHLINK_SERVER_API_KEY=6aeb82c6-e275-4538-a747-31f9abfba63c \ shlinkio/shlink-web-client`

Yes, these environment variables will be a great help. Usually, when people deploy this app, it's always to attach a SHLINK_SERVER.
