### ISSUE TITLE
[BUG] Filestash looses config on update or restart

### ISSUE THREAD

**Issue by upamanyudas** [A75G/docker-templates#82]
**Describe the bug**
Running Filestash container on unRAID. But every time the container restarts or updates, it looses all admin and share configuration. This is really frustrating to re-do the setup all over again when it restarts or updates.

**To Reproduce**
1. Update or restart the container on unRAID.

**Expected behavior**
The expectation is there is a persistent location for the configuration and it remains the unchanged through updates and restarts of the container, unless explicitly changed by the admin.

**Screenshots**

**Additional context**
This I think is basic requirement - unless I am missing something obvious.

**Comment by A75G** [comment]
I have added path to the required state/config folder
should works now but will require `chmod 777 /mnt/user/appdata/filestash/` after first boot
