### ISSUE TITLE
[Request] Zabbix Server

### ISSUE THREAD

**Issue by nowjon** [A75G/docker-templates#9]
* Docker Link: https://hub.docker.com/r/zabbix/zabbix-server-mysql, https://hub.docker.com/r/zabbix/zabbix-proxy-mysql, https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql, https://hub.docker.com/r/zabbix/zabbix-agent, https://hub.docker.com/r/zabbix/zabbix-appliance, https://hub.docker.com/r/zabbix/zabbix-java-gateway, https://hub.docker.com/r/zabbix/zabbix-java-gateway

And/or

* Git Link: 

Other: https://www.zabbix.com/container_images, https://www.zabbix.com/documentation/current/manual/installation/containers,

**Comment by A75G** [comment]
Zabbix server, web client, and agent on CA
